config/routes.rb
Rails.application.routes.draw do
 
  resources :slot_bookings
  resources :user_roles
  resources :slots
   # devise_for :users, controllers: { sessions: 'users/sessions' }
   devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
   # get '/logout' => 'users/sessions#logout'
   devise_scope :user do
   get "signup", to: "devise/registrations#new"
   get "login", to: "devise/sessions#new"
   get "logout", to: "devise/sessions#destroy"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :user
  validates :start_time, :uniqueness => {:scope => :created_date}
  validates :end_time, :uniqueness => {:scope => :created_date}

end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  layout "application"
  include UserExtension
  before_action :set_slot, only: [:show, :edit, :update, :destroy]
  
  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.where(user_id: current_user.id)
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    if current_user.user_role == "Provider"
    @slot = Slot.new
    else
      redirect_to "/slot_bookings/new", notice: 'Only Provider can create slots.'
    end 
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create

   if current_user.user_role == "Provider"
    @slot = Slot.new(slot_params.merge(user_id: current_user.id,active: true))

    respond_to do |format|
      if @slot.save 
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
    else
        redirect_to "/slot_bookings", notice: 'Only Provider can create slots.'
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:start_time, :end_time, :created_date, :user_id, :active)
    end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_with(model: slot, local: true) do |form| %>
  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
        <% slot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.number_field :start_time, :min => 1, :max => 24 %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.number_field :end_time, :min => 1, :max => 24 %>
  </div>

  <div class="field">
    <label>Scheduled Date</label>
    <%= form.datetime_select :created_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slots</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Scheduled date</th>
      <th>User</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.start_time %></td>
        <td><%= slot.end_time %></td>
        <td><%= slot.created_date %></td>
        <td><%= slot.user_id %></td>
        <td><%= slot.active %></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>

app/views/slots/new.html.erb
<h1>New Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @slot.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @slot.end_time %>
</p>

<p>
  <strong>Created date:</strong>
  <%= @slot.created_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @slot.user_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @slot.active %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>