config/routes.rb
Rails.application.routes.draw do
 
  resources :slot_bookings
  resources :user_roles
  resources :slots
   # devise_for :users, controllers: { sessions: 'users/sessions' }
   devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
   # get '/logout' => 'users/sessions#logout'
   devise_scope :user do
   get "signup", to: "devise/registrations#new"
   get "login", to: "devise/sessions#new"
   get "logout", to: "devise/sessions#destroy"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/slot_booking.rb
class SlotBooking < ApplicationRecord

    has_many :users, foreign_key: :slot_booking_id, class_name: "User"
    
    after_create :send_email    
    after_create :updateslot
   
    def send_email
    	SlotBookMailer.slot_book(self).deliver
    end

    def updateslot

       SlotBooking.all.each do |slot|
         slot = Slot.find_by(id: slot.id)  
         if slot.present?
           slot.update(active: false)
         end
       end
    end

end

app/controllers/slot_bookings_controller.rb
class SlotBookingsController < ApplicationController
  before_action :set_slot_booking, only: [:show, :edit, :update, :destroy]

  # GET /slot_bookings
  # GET /slot_bookings.json
  def index
    @slot_bookings = SlotBooking.where(user_id: current_user.id)
  end

  # GET /slot_bookings/1
  # GET /slot_bookings/1.json
  def show
  end

  # GET /slot_bookings/new
  def new
    @slot_booking = SlotBooking.new
  end

  # GET /slot_bookings/1/edit
  def edit
  end

  # POST /slot_bookings
  # POST /slot_bookings.json
  def create
    @slot_booking = SlotBooking.new(slot_booking_params)

    respond_to do |format|
      if @slot_booking
        params[:slot_booking][:slot_id].each do |slot|
         SlotBooking.create(name: @slot_booking.name,user_id: current_user.id, slot_id: slot,email: @slot_booking.email,mobile: @slot_booking.mobile,active: true)
        end
        format.html { redirect_to @slot_booking, notice: 'Slot booking was successfully created.' }
        format.json { render :show, status: :created, location: @slot_booking }
      else
        format.html { render :new }
        format.json { render json: @slot_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slot_bookings/1
  # PATCH/PUT /slot_bookings/1.json
  def update
    respond_to do |format|
      if @slot_booking.update(slot_booking_params)
        format.html { redirect_to @slot_booking, notice: 'Slot booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot_booking }
      else
        format.html { render :edit }
        format.json { render json: @slot_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slot_bookings/1
  # DELETE /slot_bookings/1.json
  def destroy
    @slot_booking.destroy
    respond_to do |format|
      format.html { redirect_to slot_bookings_url, notice: 'Slot booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot_booking
      @slot_booking = SlotBooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_booking_params
      params.require(:slot_booking).permit(:name, :user_id, :slot_id, :email, :mobile, :active)
    end
end

app/helpers/slot_bookings_helper.rb
module SlotBookingsHelper
end

app/views/slot_bookings/_form.html.erb
<%= form_with(model: slot_booking, local: true) do |form| %>
  <% if slot_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot_booking.errors.count, "error") %> prohibited this slot_booking from being saved:</h2>

      <ul>
        <% slot_booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>
  <div class="row">
    <div class="col-sm-12">  
      <label>Slots</label>
        <% if current_user.user_role.try(:name) == "Organization" %> 
            <% @slots = Slot.all %>
        <% elsif current_user.user_role.try(:name) == "Agent" %>   
            <% @slots = Slot.all.where(active: true) %>
        <% end %>
        <% if @slots.present? %>
          <% @slots.each do |slot| %>
            <div class="col-sm-1">
                <%= check_box_tag "slot_booking[slot_id][]", slot.id %>
                <label for="slot<%= slot.id %>"><%= slot.start_time %>-<%= slot.end_time %></label>             
            </div>
          <% end %>
        <% end %>
    </div>
  </div>

  <div class="actions">
        <button type="submit" class="subbtn" class="btn btn-success">Submit</button>
  </div>
<% end %>

app/views/slot_bookings/edit.html.erb
<h1>Editing Slot Booking</h1>

<%= render 'form', slot_booking: @slot_booking %>

<%= link_to 'Show', @slot_booking %> |
<%= link_to 'Back', slot_bookings_path %>

app/views/slot_bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slot Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Slot</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slot_bookings.each do |slot_booking| %>
      <tr>
        <td><%= slot_booking.name %></td>
        <td><%= slot_booking.user_id %></td>
        <td><%= slot_booking.slot_id %></td>
        <td><%= slot_booking.email %></td>
        <td><%= slot_booking.mobile %></td>
        <td><%= slot_booking.active %></td>
        <td><%= link_to 'Show', slot_booking %></td>
        <td><%= link_to 'Edit', edit_slot_booking_path(slot_booking) %></td>
        <td><%= link_to 'Destroy', slot_booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot Booking', new_slot_booking_path %>

app/views/slot_bookings/new.html.erb
<h1>New Slot Booking</h1>

<%= render 'form', slot_booking: @slot_booking %>

<%= link_to 'Back', slot_bookings_path %>

app/views/slot_bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slot_booking.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @slot_booking.user_id %>
</p>

<p>
  <strong>Slot:</strong>
  <%= @slot_booking.slot_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @slot_booking.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @slot_booking.mobile %>
</p>

<p>
  <strong>Active:</strong>
  <%= @slot_booking.active %>
</p>

<%= link_to 'Edit', edit_slot_booking_path(@slot_booking) %> |
<%= link_to 'Back', slot_bookings_path %>